"""用 SciPy 生成独立的窗口末端 Savitzky-Golay 系数参考。"""

from pathlib import Path

import scipy
from scipy.signal import savgol_coeffs


def main() -> None:
    lines = [
        f"// Generated by SciPy {scipy.__version__}; regenerate with generate_reference.py.",
        "// Independent savgol_coeffs reference: pos=window-1, delta=1, use='dot'.",
        "#pragma once",
        "struct Struct_Polynomial_Reference",
        "{",
        "    unsigned Order, Window_Size;",
        "    double Coefficient[4][33];",
        "};",
        "static const Struct_Polynomial_Reference POLYNOMIAL_REFERENCES[] = {",
    ]
    for order in range(4):
        for window in range(order + 1, 34):
            lines.append(f"    {{{order}, {window}, {{")
            for derivative in range(4):
                coefficients = savgol_coeffs(
                    window, order, deriv=derivative, pos=window - 1, use="dot"
                )
                lines.append("        {")
                for start in range(0, window, 4):
                    values = coefficients[start : start + 4]
                    lines.append(
                        "            " + ", ".join(f"{x:.17g}" for x in values) + ","
                    )
                lines.append("        },")
            lines.append("    }},")
    lines.append("};")
    Path(__file__).with_name("reference_coefficients.h").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
